apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes 
      rolearn: arn:aws:iam::791829802329:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-UNIIY0R06WCN
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::791829802329:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-01T22:42:43Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1849"
  uid: 28f3d98c-b7b2-4f4a-8132-8e78687d1edc
